name: firebase_auth_desktop
description: Windows and Linux implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.2-flipper

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  desktop_webview_auth: ^0.0.8
  firebase_auth: 4.8.0
  firebase_auth_dart:
    git:
      url: git@github.com:managry/flutterfire_desktop_2023_10.git
      ref: main
      path: packages/firebase_auth/firebase_auth_dart
  firebase_auth_platform_interface: ^6.17.0-flipper-version
  # firebase_core: ^2.16.0
  firebase_core: ^2.16.0
  firebase_core_dart:
    git:
      url: git@github.com:managry/flutterfire_desktop_2023_10.git
      ref: main
      path: packages/firebase_core/firebase_core_dart
  flutter:
    sdk: flutter
  meta: ^1.3.0

dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  async: ^2.8.1
  firebase_core_platform_interface: 4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.2

flutter:
  plugin:
    implements: firebase_auth
    platforms:
      # TODO when doing development on macOS, uncomment this.
      # macos:
      #   dartPluginClass: FirebaseAuthDesktop
      #   pluginClass: none
      linux:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none

false_secrets:
  - /example/**
